---
- name: install deps
  yum: >
    pkg={{item}}
    state=installed
  with_items:
    - python-pip
    - python-devel

- name: install python module consulate
  pip: >
    name={{item}}
  with_items:
    - tornado
    - consulate
